import { useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ShieldCheck, SealCheck, ArrowRight } from '@phosphor-icons/react'
import { Brand } from '../components/Brand'
import type { LotAssessment } from '../types'
import { useReveal, money, formatDate, useAutoScrollHeader } from '../hooks/useAnimations'

import { useStore } from "../store"

export function DealerVerify() {
  const reports = useStore(state => state.reports)
  const notify = useStore(state => state.notify)
  const { code } = useParams<{ code?: string }>()
  const [input, setInput] = useState(code || '')
  const report =
    reports.find((r) => r.code.toLowerCase() === input.trim().toLowerCase()) ||
    (code ? reports[0] : null)
  const ref = useReveal([report])
  const { isHidden, isScrolled } = useAutoScrollHeader()

  const handleVerify = () => {
    const found = reports.find(
      (r) => r.code.toLowerCase() === input.trim().toLowerCase()
    )
    if (!found) {
      notify('Try the sample code shown below')
    }
  }

  return (
    <main className="dealer-page" ref={ref}>
      <header className={`dealer-header ${isHidden ? 'header-hidden' : ''} ${isScrolled ? 'header-scrolled' : ''}`} data-reveal-tier="3">
        <Brand />
        <Link to="/" className="subtle-link">
          Farmer portal <ArrowRight size={15} />
        </Link>
      </header>

      <section className="dealer-content" data-reveal-tier="2">
        {!report ? (
          <>
            <div className="dealer-shield">
              <ShieldCheck size={32} weight="fill" />
            </div>
            <span className="eyebrow">Procurement center verification</span>
            <h1 data-reveal-tier="1">Check an OnionGrade report.</h1>
            <p data-reveal-tier="3">
              Enter the code supplied by the farmer to review a quality assessment.
            </p>
            <div className="verify-input">
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value.toUpperCase())}
                placeholder="e.g. OG-2026-01577"
                aria-label="Report code"
              />
              <button type="button" onClick={handleVerify}>
                Verify
              </button>
            </div>
            <small>Demo report code: {reports[0]?.code || 'OG-2026-01577'}</small>
          </>
        ) : (
          <>
            <div className="dealer-report-top">
              <span className="verified">
                <SealCheck size={17} weight="fill" /> Report verified
              </span>
              <span>{formatDate(report.capturedAt)}</span>
            </div>
            <h1 data-reveal-tier="1">Lot quality verified.</h1>
            <p data-reveal-tier="3">
              {report.code} · {report.variety} · {report.weight.toLocaleString('en-IN')} kg
            </p>
            <div className="dealer-summary">
              <div>
                <b>{report.metrics.gradeA}%</b>
                <span>Grade A</span>
              </div>
              <div>
                <b>{report.metrics.urs}%</b>
                <span>URS</span>
              </div>
              <div>
                <b>{money(report.pricing.fairPrice)}</b>
                <span>Fair / kg</span>
              </div>
            </div>
            <div className="dealer-note">
              <ShieldCheck size={18} weight="fill" />
              <span>
                This assessment is time-stamped, image-backed, and generated by OnionGrade’s demo analysis engine.
              </span>
            </div>
            <Link className="button button-primary" to="/assessment">
              Start your own assessment <ArrowRight size={17} />
            </Link>
          </>
        )}
      </section>
    </main>
  )
}
